# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

i = 1
fib_numbers = [1, 2]
even_fib_numbers = []
while true
  total = fib_numbers.sum
  if even_fib_numbers.sum < 4000000
    num = fib_numbers[i] + fib_numbers[i - 1]
    fib_numbers << num
    if fib_numbers[i].even? == true
      even_fib_numbers << fib_numbers[i]
    end
    i += 1
  else
    break
  end
end

p even_fib_numbers.sum